[package]
name = "WindowTool"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-service = "0.8.0"
dialoguer = "0.11"
env_logger = "0.11.8"

[build-dependencies]
winres = "0.1"

[[bin]]
name = "WindowTool"
path = "src/build.rs"
